config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/dashboard", to: "dashboard#index"  
    resources :problems
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/problem.rb
class Problem < ApplicationRecord
  has_rich_text :content
  
  enum difficulty: %w(regular, challenge)
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    @problems = Problem.all
  end
end 

app/controllers/admin/problems_controller.rb
class Admin::ProblemsController < ApplicationController
  def new
    @problem = Problem.new
  end

  def create
    Problem.create(problem_params)
    redirect_to admin_dashboard_path
  end

  def show
    @problem = Problem.find(params[:id])
  end

  def destroy
    Problem.delete(params[:id])
    redirect_to admin_dashboard_path
  end


  private

    def problem_params
      params.permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/dashboard/index.html.erb
<h1> Problems Index </h1>

<% @problems.each do |problem| %>
  <p>
    <%= problem.title %>
    <br><hr>
    <%= problem.content %>
    <br><hr>
    <br>
    <%= link_to "Show", admin_problem_path(problem) %>
    <%= link_to "Edit", edit_admin_problem_path(problem) %>
  </p>
<% end %>

<%= button_to "Create Problem", new_admin_problem_path, method: :get %>

app/views/admin/problems/new.html.erb
<%# app/views/messages/_form.html.erb %>
<%= form_with url: "/admin/problems", model: @message do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br><hr>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/problems/show.html.erb
  <p>
    <%= @problem.title %>
    <br><hr>
    <%= @problem.content %>
    <br><hr>
    <br>
    <%= link_to "Show", admin_problem_path(@problem) %>
    <%= link_to "Edit", edit_admin_problem_path(@problem) %>
    <%= button_to "Delete", admin_problem_path(@problem), method: :delete, data: { confirm: "Are you sure?" } %>
  </p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarmupRedux</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>